name: 'Local Drupal Dev Recipe'
description: 'Custom recipe for installing initial config for local Drupal development.'

install:
  - admin_toolbar_tools
  - devel
  - kint
  - emulsify_tools

config:
  actions:
    devel.settings:
      simple_config_update:
        devel_dumper: 'kint'
